### ISSUE TITLE
conflicts between attempted installs of lash-0.5.4-25.fc25.i686 and lash-0.5.4-25.fc25.x86_64

### ISSUE THREAD

**Issue by patkub** [patkub/antuple-fedora#1]
2017-02-26 21:03:02,939: Error Summary
2017-02-26 21:03:02,939: -------------
2017-02-26 21:03:02,939: Traceback (most recent call last):
2017-02-26 21:03:02,939: File "/usr/lib64/python3.5/site-packages/pyanaconda/packaging/dnfpayload.py", line 236, in do_transaction
2017-02-26 21:03:02,939: base.do_transaction(display=display)
2017-02-26 21:03:02,939: File "/usr/lib/python3.5/site-packages/dnf/base.py", line 591, in do_transaction
2017-02-26 21:03:02,939: self._trans_error_summary(errstring))
2017-02-26 21:03:02,939: dnf.exceptions.Error: Transaction check error:
2017-02-26 21:03:02,939: file /usr/share/doc/lash/lash-manual/lash-manual.html conflicts between attempted installs of lash-0.5.4-25.fc25.i686 and lash-0.5.4-25.fc25.x86_64

**Comment by patkub** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1266672

**Comment by patkub** [comment]
```
%include fedora-live-base.ks

repo --name=google-chrome --baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch

%packages
google-chrome
%end

%post
/bin/bash
echo Antuple Fedora
echo Setting hostname...
hostnamectl set-hostname laptop.antuple
echo Updating packages...
dnf update
%end
```

**Comment by patkub** [comment]
Stuck generating initramfs for an hour...

**Comment by patkub** [comment]
testing with

google-chrome
vlc
python-vlc
npapi-vl

**Comment by patkub** [comment]
```
2017-02-26 23:38:56,562: Configuring installed system
2017-02-26 23:38:56,640: .
2017-02-26 23:38:56,641: Creating users
2017-02-26 23:38:56,641: .BDB2053 Freeing read locks for locker 0x1: 11166/139794155968256
2017-02-26 23:38:56,642: BDB2053 Freeing read locks for locker 0x3: 11166/139794155968256
2017-02-26 23:38:56,642: BDB2053 Freeing read locks for locker 0x4: 11166/139794155968256
2017-02-26 23:38:56,642: BDB2053 Freeing read locks for locker 0x5: 11166/139794155968256
...
2017-02-26 23:38:56,644: BDB2053 Freeing read locks for locker 0x14: 11166/139794155968256
2017-02-26 23:38:56,647: 
2017-02-26 23:38:56,647: Configuring addons
2017-02-26 23:39:10,059: .
2017-02-26 23:39:10,059: Generating initramfs
```

**Comment by patkub** [comment]
Get a boot iso from https://download.fedoraproject.org/pub/fedora/linux/releases/25/Workstation/x86_64/os/images/boot.iso

**Comment by patkub** [comment]
mock -r fedora-25-x86_64 --copyin '/home/patka/Downloads/boot.iso' remix/

**Comment by patkub** [comment]
livemedia-creator --make-iso --iso=boot.iso --ks=flat-antuple-fedora.ks
